#pragma once

// Thanks microsoft but also fuck you no one on our developer team likes you
// https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

#define KEY_LMOUSE 0x01
#define KEY_RMOUSE 0x02
#define KEY_CANCEL 0x03
#define KEY_MMOUSE 0x04
#define KEY_MOUSE_5 0x05
#define KEY_MOUSE_6 0x06

#define KEY_BACK 0x08
#define KEY_TAB 0x09
#define KEY_CLEAR 0x0C
#define KEY_RETURN 0x0D
#define KEY_SHIFT 0x10
#define KEY_CONTROL 0x11
#define KEY_ALT 0x12
#define KEY_PAUSE 0x13
#define KEY_CAPSLOCK 0x14
#define KEY_ESCAPE 0x1B
#define KEY_SPACE 0x20
#define KEY_PAGEUP 0x21
#define KEY_PAGEDOWN 0x22
#define KEY_END 0x23
#define KEY_HOME 0x24
#define KEY_LEFT_ARROW 0x25
#define KEY_UP_ARROW 0x26
#define KEY_RIGHT_ARROW 0x27
#define KEY_DOWN_ARROW 0x28
#define KEY_SELECT 0x29
#define KEY_PRINT 0x2A
#define KEY_EXECUTE 0x2B
#define KEY_PRINT_SCREEN 0x2C
#define KEY_INSERT 0x2D
#define KEY_DELETE 0x2E
#define KEY_HELP 0x2F
#define KEY_0 0x30
#define KEY_1 0x31
#define KEY_2 0x32
#define KEY_3 0x33
#define KEY_4 0x34
#define KEY_5 0x35
#define KEY_6 0x36
#define KEY_7 0x37
#define KEY_8 0x38
#define KEY_9 0x39
#define KEY_A 0x41
#define KEY_B 0x42
#define KEY_C 0x43
#define KEY_D 0x44
#define KEY_E 0x45
#define KEY_F 0x46
#define KEY_G 0x47
#define KEY_H 0x48
#define KEY_I 0x49
#define KEY_J 0x4A
#define KEY_K 0x4B
#define KEY_L 0x4C
#define KEY_M 0x4D
#define KEY_N 0x4E
#define KEY_O 0x4F
#define KEY_P 0x50
#define KEY_Q 0x51
#define KEY_R 0x52
#define KEY_S 0x53
#define KEY_T 0x54
#define KEY_U 0x55
#define KEY_V 0x56
#define KEY_W 0x57
#define KEY_X 0x58
#define KEY_Y 0x59
#define KEY_Z 0x5A
#define KEY_LEFT_WIN 0x5B
#define KEY_RIGHT_WIN 0x5C
#define KEY_APPS 0x5D
#define KEY_SLEEP 0x5F
#define KEY_NUMPAD_0 0x60
#define KEY_NUMPAD_1 0x61
#define KEY_NUMPAD_2 0x62
#define KEY_NUMPAD_3 0x63
#define KEY_NUMPAD_4 0x64
#define KEY_NUMPAD_5 0x65
#define KEY_NUMPAD_6 0x66
#define KEY_NUMPAD_7 0x67
#define KEY_NUMPAD_8 0x68
#define KEY_NUMPAD_9 0x69
#define KEY_MULTIPLY 0x6A
#define KEY_ADD 0x6B
#define KEY_SEPARATOR 0x6C
#define KEY_SUBTRACT 0x6D
#define KEY_DECIMAL 0x6E
#define KEY_DIVIDE 0x6F
#define KEY_F1 0x70
#define KEY_F2 0x71
#define KEY_F3 0x72
#define KEY_F4 0x73
#define KEY_F5 0x74
#define KEY_F6 0x75
#define KEY_F7 0x76
#define KEY_F8 0x77
#define KEY_F9 0x78
#define KEY_F10 0x79
#define KEY_F11 0x7A
#define KEY_F12 0x7B
#define KEY_NUMLOCK 0x90
#define KEY_SCROLL_LOCK 0x91
#define KEY_LSHIFT 0xA0
#define KEY_RSHIFT 0xA1
#define KEY_LCONTROL 0xA2
#define KEY_RCONTROL 0xA3
#define KEY_LMENU 0xA4
#define KEY_RMENU 0xA5
#define KEY_BROWSER_BACK 0xA6
#define KEY_BROWSER_FORWARD 0xA7
#define KEY_BROWSER_REFRESH 0xA8
#define KEY_BROWSER_STOP 0xA9
#define KEY_BROWSER_SEARCH 0xAA
#define KEY_BROWSER_FAVORITES 0xAB
#define KEY_BROWSER_HOME 0xAC
#define KEY_VOLUME_MUTE 0xAD
#define KEY_VOLUME_DOWN 0xAE
#define KEY_VOLUME_UP 0xAF
#define KEY_MEDIA_NEXT_TRACK 0xB0
#define KEY_MEDIA_PREV_TRACK 0xB1
#define KEY_MEDIA_STOP 0xB2
#define KEY_MEDIA_PLAY_PAUSE 0xB3
#define KEY_LAUNCH_MAIL 0xB4
#define KEY_LAUNCH_MEDIA_SELECT 0xB5
#define KEY_LAUNCH_APP1 0xB6
#define KEY_LAUNCH_APP2 0xB7
#define KEY_OEM_1 0xBA
#define KEY_OEM_PLUS 0xBB
#define KEY_OEM_COMMA 0xBC
#define KEY_OEM_MINUS 0xBD
#define KEY_OEM_PERIOD 0xBE
#define KEY_OEM_2 0xBF
#define KEY_OEM_3 0xC0
#define KEY_OEM_4 0xDB
#define KEY_OEM_5 0xDC
#define KEY_OEM_6 0xDD
#define KEY_OEM_7 0xDE
#define KEY_OEM_8 0xDF
#define KEY_OEM_102 0xE2
#define KEY_PROCESSKEY 0xE5
#define KEY_PACKET 0xE7
#define KEY_ATTN 0xF6
#define KEY_CRSEL 0xF7
#define KEY_EXSEL 0xF8
#define KEY_EREOF 0xF9
#define KEY_PLAY 0xFA
#define KEY_ZOOM 0xFB
#define KEY_NONAME 0xFC
#define KEY_PA1 0xFD
#define KEY_OEM_CLEAR 0xFE

#define KEY_ENTER KEY_RETURN
#define KEY_BACKSPACE KEY_BACK
#define KEY_LWIN KEY_LEFT_WIN
#define KEY_RWIN KEY_RIGHT_WIN
#define KEY_CONTEXT_MENU KEY_APPS
#define KEY_PAUSE_BREAK KEY_PAUSE
#define KEY_PAGE_UP KEY_PAGEUP
#define KEY_PAGE_DOWN KEY_PAGEDOWN
#define KEY_UP KEY_UP_ARROW
#define KEY_DOWN KEY_DOWN_ARROW
#define KEY_LEFT KEY_LEFT_ARROW
#define KEY_RIGHT KEY_RIGHT_ARROW
#define KEY_DECIMAL_POINT KEY_DECIMAL
#define KEY_NUM_LOCK KEY_NUMLOCK
#define KEY_CTRL_LEFT KEY_LCONTROL
#define KEY_CTRL_RIGHT KEY_RCONTROL
#define KEY_SHIFT_LEFT KEY_LSHIFT
#define KEY_SHIFT_RIGHT KEY_RSHIFT
#define KEY_ALT_LEFT KEY_LMENU
#define KEY_ALT_RIGHT KEY_RMENU
#define KEY_MUTE KEY_VOLUME_MUTE
#define KEY_VOL_DOWN KEY_VOLUME_DOWN
#define KEY_VOL_UP KEY_VOLUME_UP
#define KEY_NEXT_TRACK KEY_MEDIA_NEXT_TRACK
#define KEY_PREV_TRACK KEY_MEDIA_PREV_TRACK
#define KEY_STOP_MEDIA KEY_MEDIA_STOP
#define KEY_PLAY_PAUSE KEY_MEDIA_PLAY_PAUSE
#define KEY_EMAIL KEY_LAUNCH_MAIL
#define KEY_CALCULATOR KEY_LAUNCH_APP1
#define KEY_MY_COMPUTER KEY_LAUNCH_APP2
#define KEY_COLON KEY_OEM_1
#define KEY_PLUS KEY_OEM_PLUS
#define KEY_COMMA KEY_OEM_COMMA
#define KEY_MINUS KEY_OEM_MINUS
#define KEY_PERIOD KEY_OEM_PERIOD
#define KEY_SLASH KEY_OEM_2
#define KEY_TILDE KEY_OEM_3
#define KEY_LEFT_BRACKET KEY_OEM_4
#define KEY_BACKSLASH KEY_OEM_5
#define KEY_RIGHT_BRACKET KEY_OEM_6
#define KEY_QUOTE KEY_OEM_7
#define KEY_LESS_THAN KEY_OEM_102